[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "v20.18.0"
  ROLLUP_SKIP_NODEJS_NATIVE = "1"

# Handle SPA routing (important for React + Solana wallet dapp)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
